SYMPTOME : commande de 800 € HT, client Standard, facturée avec 18 % de remise (> plafond 15 %, > palier attendu 0 %)
ZONE     : DiscountPolicy.computeBestDiscount (branche remise contractuelle) — [DiscountPolicy.java](src/main/java/com/novatech/orders/domain/DiscountPolicy.java#L99-L101) ; plafond défini [DiscountPolicy.java](src/main/java/com/novatech/orders/domain/DiscountPolicy.java#L17) et vérifié par `checkRateWithinCap` [DiscountPolicy.java](src/main/java/com/novatech/orders/domain/DiscountPolicy.java#L117-L119) — jamais appelée depuis `computeBestDiscount`

| # | Livraison (commit ou MR) | Fichiers touchés dans la zone | Ticket lié | Confiance |
|---|---|---|---|---|
| 1 | `5e040d07` — « orders-api : socle du tunnel de commande » (2026-09-20) | [DiscountPolicy.java](src/main/java/com/novatech/orders/domain/DiscountPolicy.java) — `computeBestDiscount` compare `contractRate` au taux du barème mais ne le fait jamais passer par `checkRateWithinCap` avant de le retenir comme `bestRate` | NOVA-3 (bareme volume, acceptance criteria exige explicitement le plafond de 15 % y compris hors barème) | forte — c'est le commit qui a créé la méthode, et le code livré ne couvre pas le scénario « plafond global » que le ticket décrit pourtant en critère d'acceptation |
| 2 | ticket NOVA-5 / MR **!124** citée dans sa description | [DiscountPolicy.java](src/main/java/com/novatech/orders/domain/DiscountPolicy.java#L63-L69) — `resolveTier` appelle toujours `customer.getCategory().toUpperCase()` sans le null-safe `Optional` décrit dans le diff du ticket ; `DEFAULT_CATEGORY` (ligne 20) est déclarée mais jamais utilisée | NOVA-5 (statut Terminé(e), corrigé « par MR !124 ») | faible — même fichier, mais bug différent (NPE sur catégorie nulle, pas un dépassement de taux) ; lié seulement par proximité de code, pas par le symptôme de cette nuit |
| 3 | `486f3b1f` — « Atelier outillé : connecteurs MCP et guide de démarrage » (2026-09-20) | README.md, .vscode/mcp.json — ne touche aucun fichier de la zone | aucun | faible — présent dans la fenêtre de deux semaines mais hors zone métier |

PROCHAINE ACTION SUGGEREE : relire la fiche du client concerné (`contractDiscountRate` en base) pour confirmer que la valeur stockée est bien 18 %, et vérifier si ce champ est alimenté sans contrôle depuis un import ou une saisie manuelle.
NON VERIFIE : la merge request !124 citée par le ticket NOVA-5 n'existe pas dans la liste des MR du projet GitLab interrogé (résultat vide) — je n'ai pas pu confirmer si le diff décrit dans le ticket a réellement été fusionné ailleurs ou jamais livré. Je n'ai pas non plus consulté la facture Sage ni relancé les tests (`DiscountPolicyTest`, `OrderServiceTest`) pour reproduire le cas à 800 € / 18 %.